package views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import dao.DaoCliente;
import dao.DaoOrdemDeServico;
import dao.DaoTecnico;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.OperacaoEnum;
import model.OrdemServico;
import model.Tecnico;

/**
 *
 * @author jbila
 */
public class FrmOs extends javax.swing.JFrame {

    private final DaoOrdemDeServico daoOrdemDeServico;
    private final DaoCliente daoCliente;
    private final DaoTecnico daoTecnico;

    /**
     * Creates new form FrmCliente
     */
    public FrmOs() {
        initComponents();
        daoOrdemDeServico = new DaoOrdemDeServico();
        daoCliente=new DaoCliente();
        daoTecnico=new DaoTecnico();
        preencherTabela();
        fillCliente();
        fillTecnico();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtServico = new javax.swing.JTextField();
        txtAvaria = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboStatus = new javax.swing.JComboBox<>();
        cboTecnico = new javax.swing.JComboBox<>();
        cboCliente = new javax.swing.JComboBox<>();
        txtValor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEquipamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel1.setText("Equipamento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTO DE ORDEM DE SERVIÇO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel3.setText("Cliente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 60, 20));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel4.setText("Serviço");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 124, 70, 20));
        jPanel1.add(txtServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 340, -1));
        jPanel1.add(txtAvaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 340, -1));

        txtId.setEditable(false);
        txtId.setForeground(new java.awt.Color(255, 0, 0));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 400, -1));

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Avaria", "Servico", "Valor", "Status", "Cliente", "Tecnico", "Operacao"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 950, 260));

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        btnDelete.setBackground(new java.awt.Color(0, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setActionCommand("");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel6.setText("Avaria");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, 20));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel7.setText("Status");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 60, 20));

        cboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAGO", "NAO_PAGO" }));
        jPanel1.add(cboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 400, -1));

        jPanel1.add(cboTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 400, -1));
        jPanel1.add(cboCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 400, -1));
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 340, -1));

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel8.setText("Valor");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 50, 20));

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 1, 12)); // NOI18N
        jLabel9.setText("Tecnico");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));
        jPanel1.add(txtEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 340, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        OrdemServico ordemServico = new OrdemServico();
        ordemServico.setAvaria(txtAvaria.getText());
        ordemServico.setServico(txtServico.getText());
        ordemServico.setOperacao(OperacaoEnum.ENTRADA.toString());
        ordemServico.setValor(Double.parseDouble(txtValor.getText()));
        ordemServico.setEquipamento(txtEquipamento.getText());

        ordemServico.setStatus(cboStatus.getSelectedItem().toString());
        
        Cliente cliente=(Cliente) cboCliente.getSelectedItem();
        ordemServico.setCliente(cliente);
        Tecnico tecnico=(Tecnico)cboTecnico.getSelectedItem();
        ordemServico.setTecnico(tecnico);
        
        double iva = Double.parseDouble(txtValor.getText()) * 0.16;
        ordemServico.setIva(iva);
     

        try {

            if (!txtEquipamento.getText().isEmpty() && !txtServico.getText().isEmpty()) {
                try {
                    daoOrdemDeServico.save(ordemServico);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmOs.class.getName()).log(Level.SEVERE, null, ex);
                }
                limpar();
                preencherTabela();
            } else {
                JOptionPane.showMessageDialog(btnSave, "Preencha os campos");
            }

        } catch (HeadlessException ex) {
            // TODO Auto-generated catch block

        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        selection();
    }//GEN-LAST:event_tableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (!txtId.getText().isEmpty()) {
            OrdemServico ordemServico = new OrdemServico();
            ordemServico.setAvaria(txtAvaria.getText());
            ordemServico.setServico(txtServico.getText());
            ordemServico.setOperacao(OperacaoEnum.ENTRADA.toString());
            ordemServico.setValor(Double.parseDouble(txtValor.getText()));
            ordemServico.setEquipamento(txtEquipamento.getText());
            ordemServico.setStatus(cboStatus.getSelectedItem().toString());
            Tecnico tecnico=(Tecnico)cboTecnico.getSelectedItem();
        ordemServico.setTecnico(tecnico);
            Cliente cliente=(Cliente) cboCliente.getSelectedItem();
            ordemServico.setCliente(cliente);
            double iva = Double.parseDouble(txtValor.getText()) * 0.16;
            ordemServico.setIva(iva);
            ordemServico.setId(Integer.parseInt(txtId.getText()));

            try {
                daoOrdemDeServico.update(ordemServico);
                preencherTabela();
            } catch (SQLException e1) {
                // TODO Auto-generated catch block

            }
        } else {
            JOptionPane.showMessageDialog(btnUpdate, "Selecione a linha na Tabela");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmOs frame = new FrmOs();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);

            }
        });
    }

    /*FOR DEVELOPER*/
    private void delete() {
        if (!txtId.getText().isEmpty()) {
            int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?",
                    "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (confirmation == JOptionPane.YES_OPTION) {
                daoOrdemDeServico.delete(Integer.parseInt(txtId.getText()));
                preencherTabela();
                limpar();
            } else {

                JOptionPane.showMessageDialog(table, "Selecione a linha na tabela");
            }

        }

    }
    //END OF DELETE

    /*---------limpar campos----------*/
    private void limpar() {
        txtAvaria.setText("");
        txtEquipamento.setText("");
        txtServico.setText("");
        txtServico.setText("");
        txtValor.setText("");
        txtId.setText("");

    }

    // preecher tabela
    private void preencherTabela() {

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        Object[] row = new Object[9];
        model.setRowCount(0);// limpar a tabela
        List<OrdemServico> o = daoOrdemDeServico.findAll();
        for (int i = 0; i < o.size(); i++) {
            row[0] = o.get(i).getId();
            row[1] = o.get(i).getEquipamento();
            row[2] = o.get(i).getAvaria();
            row[3] = o.get(i).getServico();
            row[4] = o.get(i).getValor();
            row[5] = o.get(i).getStatus();
            row[6] = o.get(i).getCliente();
            row[7] = o.get(i).getTecnico();
             row[8] = o.get(i).getOperacao();
            model.addRow(row);
        }

    }

    private void fillTecnico() {
         List<Tecnico> tecnicos=daoTecnico.findAll();
        for (Tecnico tecnico : tecnicos) {
            cboTecnico.addItem(tecnico);
        }

    }

    private void fillCliente() {
        List<Cliente> clientes=daoCliente.findAll();
        for (Cliente cliente : clientes) {
            cboCliente.addItem(cliente);
        }
    }

    private void selection() {
        try {
            int selectedRow = table.getSelectedRow();
            if (selectedRow >= 0) {

                Object id = table.getValueAt(selectedRow, 0);
                Object equipamento = table.getValueAt(selectedRow, 1);
                Object avaria = table.getValueAt(selectedRow, 2);
                Object servico = table.getValueAt(selectedRow, 3);
                Object valor = table.getValueAt(selectedRow, 4);
                Object status = table.getValueAt(selectedRow, 5);
                Object cliente = table.getValueAt(selectedRow, 6);
                Object tecnico = table.getValueAt(selectedRow, 7);

                txtId.setText(id.toString());
                txtEquipamento.setText(equipamento.toString());
                txtAvaria.setText(avaria.toString());
                txtServico.setText(servico.toString());
                cboStatus.addItem(cboStatus.toString());
                txtValor.setText(valor.toString());
                cboTecnico.addItem(tecnico.toString());
                cboStatus.addItem(status.toString());
                cboCliente.addItem(cliente.toString());

            }
        } catch (NullPointerException ex) {

        }

    }
    //END 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Object> cboCliente;
    private javax.swing.JComboBox<String> cboStatus;
    private javax.swing.JComboBox<Object> cboTecnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtAvaria;
    private javax.swing.JTextField txtEquipamento;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtServico;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
