package views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import dao.DaoOrdemDeServico;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.OperacaoEnum;
import model.OrdemServico;

/**
 *
 * @author jbila
 */
public class FrmOsSaida extends javax.swing.JFrame {

    private final DaoOrdemDeServico daoOrdemDeServico;

    /**
     * Creates new form FrmCliente
     */
    public FrmOsSaida() {
        initComponents();
        daoOrdemDeServico = new DaoOrdemDeServico();
        preencherTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnEntregar = new javax.swing.JButton();
        jDateChooserData2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" SAIDA DO EQUIPAMENTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Avaria", "Servico", "Valor", "Status", "Cliente", "Tecnico", "Data", "Operacao"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1020, 410));

        btnEntregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-eye-24.png"))); // NOI18N
        btnEntregar.setText("entregar");
        btnEntregar.setToolTipText("Procurar");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 210, -1));

        jDateChooserData2.setToolTipText("Selecione a Segunda Data");
        jPanel1.add(jDateChooserData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 140, -1));

        jLabel3.setText("entrada");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 100, 20));

        lblId.setForeground(new java.awt.Color(255, 0, 0));
        lblId.setText("ID:");
        jPanel1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1030, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        selection();
    }//GEN-LAST:event_tableMouseClicked

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed

        OrdemServico ordemServico = daoOrdemDeServico.findById(Integer.parseInt(lblId.getText()));

        if (ordemServico != null) {

            if (ordemServico.getStatus().equals("PAGO")) {
                try {
                    ordemServico.setOperacao(OperacaoEnum.SAIDA.toString());
                    ordemServico.setCliente(ordemServico.getCliente());
                    ordemServico.setTecnico(  ordemServico.getTecnico());
                    daoOrdemDeServico.update(ordemServico);
                    preencherTabela();
                } catch (SQLException ex) {
                    Logger.getLogger(FrmOsSaida.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "FAÇA O PAGAMENTO POR FAVOR!");
            }
        }
        else{
                            JOptionPane.showMessageDialog(rootPane, "Vazio");

        }


    }//GEN-LAST:event_btnEntregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmOsSaida frame = new FrmOsSaida();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);

            }
        });
    }

    // preecher tabela
    private void preencherTabela() {
        List<OrdemServico> ordens = daoOrdemDeServico.findAll();
        showInfo(ordens);

    }

    private void showInfo(List<OrdemServico> o) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        Object[] row = new Object[10];
        model.setRowCount(0);// limpar a tabela
        for (int i = 0; i < o.size(); i++) {
            row[0] = o.get(i).getId();
            row[1] = o.get(i).getEquipamento();
            row[2] = o.get(i).getAvaria();
            row[3] = o.get(i).getServico();
            row[4] = o.get(i).getValor();
            row[5] = o.get(i).getStatus();
            row[6] = o.get(i).getCliente();
            row[7] = o.get(i).getTecnico();
            row[8] = o.get(i).getData().toString();
            row[9] = o.get(i).getOperacao();
            model.addRow(row);
        }

    }

    private void selection() {
        try {
            int selectedRow = table.getSelectedRow();
            if (selectedRow >= 0) {

                Object id = table.getValueAt(selectedRow, 0);
                Object equipamento = table.getValueAt(selectedRow, 1);
                Object avaria = table.getValueAt(selectedRow, 2);
                Object servico = table.getValueAt(selectedRow, 3);
                Object valor = table.getValueAt(selectedRow, 4);
                Object status = table.getValueAt(selectedRow, 5);
                Object cliente = table.getValueAt(selectedRow, 6);
                Object tecnico = table.getValueAt(selectedRow, 7);
                lblId.setText("" + id);

            }
        } catch (NullPointerException ex) {

        }

    }
    //END 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregar;
    private com.toedter.calendar.JDateChooser jDateChooserData2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
