package views;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import dao.DaoOrdemDeServico;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.OrdemServico;

/**
 *
 * @author jbila
 */
public class FrmOsEmitidas extends javax.swing.JFrame {

    private final DaoOrdemDeServico daoOrdemDeServico;

    /**
     * Creates new form FrmCliente
     */
    public FrmOsEmitidas() {
        initComponents();
        daoOrdemDeServico = new DaoOrdemDeServico();
        preencherTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        cboStatus = new javax.swing.JComboBox<>();
        lblSomatorioValor = new javax.swing.JLabel();
        lblSomatorioIva = new javax.swing.JLabel();
        lblLinha = new javax.swing.JLabel();
        btnProcurarPorDadas = new javax.swing.JButton();
        jDateChooserData2 = new com.toedter.calendar.JDateChooser();
        jDateChooserData = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" ORDEM DE SERVIÇO EMITIDAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-eye-24.png"))); // NOI18N
        btnSearch.setText("procurar");
        btnSearch.setToolTipText("procurar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 120, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Avaria", "Servico", "Valor", "Status", "Cliente", "Tecnico", "Data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1020, 410));

        cboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAGO", "NAO_PAGO" }));
        jPanel1.add(cboStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, -1));

        lblSomatorioValor.setBackground(new java.awt.Color(255, 0, 0));
        lblSomatorioValor.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblSomatorioValor.setText("Somatorio:");
        jPanel1.add(lblSomatorioValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, 160, 40));

        lblSomatorioIva.setBackground(new java.awt.Color(255, 0, 0));
        lblSomatorioIva.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblSomatorioIva.setText("Iva:");
        jPanel1.add(lblSomatorioIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 130, 40));

        lblLinha.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblLinha.setText("Registo");
        jPanel1.add(lblLinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 140, 40));

        btnProcurarPorDadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-eye-24.png"))); // NOI18N
        btnProcurarPorDadas.setText("procurar");
        btnProcurarPorDadas.setToolTipText("Procurar");
        btnProcurarPorDadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarPorDadasActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcurarPorDadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, -1, -1));

        jDateChooserData2.setToolTipText("Selecione a Segunda Data");
        jPanel1.add(jDateChooserData2, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 60, 140, -1));

        jDateChooserData.setToolTipText("Selecione a Primeira data");
        jPanel1.add(jDateChooserData, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 60, 170, -1));

        jLabel1.setText("De");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 20, 30));

        jLabel3.setText("Até");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 30, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1030, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String estadoActual = cboStatus.getSelectedItem().toString();
        double somatorioValor = 0.0;
        double somatorioIva = 0.0;
        int linha = 0;
        if (!estadoActual.isEmpty()) {
            List<OrdemServico> orders = daoOrdemDeServico.findAllByStatus(estadoActual);

            showInfo(orders);
            for (OrdemServico order : orders) {
                if (order.getValor() > 0) {
                    linha++;
                    somatorioIva = somatorioIva + order.getIva();
                    somatorioValor = somatorioValor + order.getValor();
                }
            }
        }
//System.out.print("IVA: "+somatorioIva+" Valor: "  +somatorioValor);
        lblSomatorioValor.setText("Somatorio: " + somatorioValor);
        lblSomatorioIva.setText("Iva: " + somatorioIva);
        lblLinha.setText("Total: " + linha);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        selection();
    }//GEN-LAST:event_tableMouseClicked

    private void btnProcurarPorDadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarPorDadasActionPerformed
        Date data = jDateChooserData.getDate();
        Date data2 = jDateChooserData2.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
        if (data != null && data2 != null) {
            // Format the Date object using the SimpleDateFormat object
            String data1_formated = sdf.format(data);
            String data2_formated = sdf.format(data2);
            List<OrdemServico> orders = daoOrdemDeServico.findAllByDate(data1_formated, data2_formated);
            showInfo(orders);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione as Data");
        }


    }//GEN-LAST:event_btnProcurarPorDadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmOsEmitidas frame = new FrmOsEmitidas();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);

            }
        });
    }

    // preecher tabela
    private void preencherTabela() {
        List<OrdemServico> ordens = daoOrdemDeServico.findAll();
        showInfo(ordens);

    }

    private void showInfo(List<OrdemServico> o) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        Object[] row = new Object[10];
        model.setRowCount(0);// limpar a tabela
        for (int i = 0; i < o.size(); i++) {
            row[0] = o.get(i).getId();
            row[1] = o.get(i).getEquipamento();
            row[2] = o.get(i).getAvaria();
            row[3] = o.get(i).getServico();
            row[4] = o.get(i).getValor();
            row[5] = o.get(i).getStatus();
            row[6] = o.get(i).getCliente();
            row[7] = o.get(i).getTecnico();
            row[8] = o.get(i).getData().toString();
                row[9] = o.get(i).getOperacao();
            model.addRow(row);
        }

    }

    private void selection() {
        try {
            int selectedRow = table.getSelectedRow();
            if (selectedRow >= 0) {

                Object id = table.getValueAt(selectedRow, 0);
                Object equipamento = table.getValueAt(selectedRow, 1);
                Object avaria = table.getValueAt(selectedRow, 2);
                Object servico = table.getValueAt(selectedRow, 3);
                Object valor = table.getValueAt(selectedRow, 4);
                Object status = table.getValueAt(selectedRow, 5);
                Object cliente = table.getValueAt(selectedRow, 6);
                Object tecnico = table.getValueAt(selectedRow, 7);

            }
        } catch (NullPointerException ex) {

        }

    }
    //END 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcurarPorDadas;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cboStatus;
    private com.toedter.calendar.JDateChooser jDateChooserData;
    private com.toedter.calendar.JDateChooser jDateChooserData2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLinha;
    private javax.swing.JLabel lblSomatorioIva;
    private javax.swing.JLabel lblSomatorioValor;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
